torchrun --nproc_per_node 1 train.py \
--task gsm8k \
--model_type 7B \
--ckpt_dir config/7B/ \
--log_dir log/train/ \
--train_file data/gsm8k/teacher.json \
--save_dir result/7B/train/ \
--max_batch_size 1 \
--accumulation_steps 4 \
--lora_rank 64 \
--eval_batch_size 24 \
--epochs 12
