torchrun --nproc_per_node 1 train_mcc.py \
--task gsm8k \
--model_type 7B \
--ckpt_dir config/7B/ \
--log_dir log/train-mcc/ \
--train_file data/gsm8k/teacher_mcc.json \
--save_dir result/7B/train-mcc/ \
--alpha 0.01 \
--max_batch_size 2 \
--accumulation_steps 2 \
--lora_rank 64 \
--eval_batch_size 24 \
--epochs 12 \
--t 1.3
